; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:esp32-s3-devkitc-1]
; platform = espressif32
; board = esp32-s3-devkitc-1
; framework = arduino

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; 指定串口
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200

; 自动下载 TM1637 驱动库
lib_deps =
    https://github.com/avishorp/TM1637.git

; 针对你 16MB Flash 的优化配置
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio

; 让 ESP32-S3 开机时启用原生 USB CDC，确保 Serial 对应 USB 串口
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
